# Server
server:
  address: 0.0.0.0

# Info
spring:
  application:
    name: webhook

info:
  developer: Felipe Gutierrez
  version: 0.0.1

# Ansible
ansible:
  projects:
  - name: ui
    path: /opt/playbooks
    command: ['ansible-playbook','ui.yml']

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: info,health,configprops